// mock-data/homeNodeChains.ts

export type HomeNodeChain = {
  id: number;
  name: string;
  stakeRequirement: string;
  hardwareSummary: string;
  homeNodeFeasible: boolean;
  validatorHomeFeasible: "yes" | "no" | "partial"; // partial = heavy or permissioned
  aprRange: string; // display text
  aprSort: number; // mid-point for sorting
  notes: string;
  category: "Polkadot" | "Cosmos" | "EVM" | "AltL1" | "L2" | "DePIN";
  hardwareScore: 1 | 2 | 3; // 1 = light, 3 = heavy
};

export const homeNodeChains: HomeNodeChain[] = [
  {
    id: 1,
    name: "Polkadot",
    stakeRequirement: "~350 DOT backing (varies)",
    hardwareSummary: "4–8 cores, 32–64GB RAM, NVMe SSD",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "6–14%",
    aprSort: 10,
    notes: "NPoS; requires backing from nominators; great for home validator rigs.",
    category: "Polkadot",
    hardwareScore: 2,
  },
  {
    id: 2,
    name: "Kusama",
    stakeRequirement: "20–50 KSM",
    hardwareSummary: "Similar to Polkadot",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "8–18%",
    aprSort: 13,
    notes: "Experimental cousin of Polkadot with higher volatility and yields.",
    category: "Polkadot",
    hardwareScore: 2,
  },
  {
    id: 3,
    name: "Ethereum",
    stakeRequirement: "32 ETH",
    hardwareSummary: "4+ cores, 32GB RAM, 2TB SSD",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "3–5%",
    aprSort: 4,
    notes: "Execution + consensus clients; capital heavy but home hardware-friendly.",
    category: "EVM",
    hardwareScore: 2,
  },
  {
    id: 4,
    name: "Polygon PoS",
    stakeRequirement: "~1–5M MATIC via delegation",
    hardwareSummary: "4 cores, 16GB RAM, SSD",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "4–7%",
    aprSort: 5,
    notes: "Delegation-based with light hardware demands.",
    category: "EVM",
    hardwareScore: 1,
  },
  {
    id: 5,
    name: "Solana",
    stakeRequirement: "Delegation-based",
    hardwareSummary: "12–24 cores, 128GB RAM, high IOPS NVMe",
    homeNodeFeasible: true,
    validatorHomeFeasible: "partial",
    aprRange: "6–8%",
    aprSort: 7,
    notes: "High-performance chain; feasible at home only with top-end hardware.",
    category: "AltL1",
    hardwareScore: 3,
  },
  {
    id: 6,
    name: "Avalanche",
    stakeRequirement: "2,000 AVAX",
    hardwareSummary: "8 cores, 32GB RAM, SSD",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "7–9%",
    aprSort: 8,
    notes: "Primary network with home-friendly validator hardware.",
    category: "EVM",
    hardwareScore: 2,
  },
  {
    id: 7,
    name: "Cosmos Hub",
    stakeRequirement: "~100 ATOM self-bond + delegators",
    hardwareSummary: "4–8 cores, 32GB RAM, NVMe",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "12–18%",
    aprSort: 15,
    notes: "Core Cosmos chain; classic home validator setup.",
    category: "Cosmos",
    hardwareScore: 2,
  },
  {
    id: 8,
    name: "Osmosis",
    stakeRequirement: "5k–10k OSMO bonded",
    hardwareSummary: "4–6 cores, 16–32GB RAM, SSD",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "10–20%",
    aprSort: 15,
    notes: "DEX chain with strong validator economics; Cosmos SDK.",
    category: "Cosmos",
    hardwareScore: 2,
  },
  {
    id: 9,
    name: "Juno",
    stakeRequirement: "~10k JUNO bonded",
    hardwareSummary: "4 cores, 16GB RAM",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "12–25%",
    aprSort: 18,
    notes: "Cosmos smart-contract chain; inflationary rewards.",
    category: "Cosmos",
    hardwareScore: 1,
  },
  {
    id: 10,
    name: "Celestia (TIA)",
    stakeRequirement: "~2,000 TIA",
    hardwareSummary: "4–8 cores, 32GB RAM, NVMe",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "5–8%",
    aprSort: 6,
    notes: "Data availability chain with light nodes + DA nodes.",
    category: "Cosmos",
    hardwareScore: 2,
  },
  {
    id: 11,
    name: "Near Protocol",
    stakeRequirement: "Seat price varies",
    hardwareSummary: "4–8 cores, 32GB RAM",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "7–11%",
    aprSort: 9,
    notes: "Sharded PoS; validator program competitive but home-friendly.",
    category: "AltL1",
    hardwareScore: 2,
  },
  {
    id: 12,
    name: "Algorand",
    stakeRequirement: "1 ALGO (participation)",
    hardwareSummary: "2–4 cores, 8GB RAM",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "3–6%",
    aprSort: 4,
    notes: "Pure PoS; extremely easy to run participation nodes.",
    category: "AltL1",
    hardwareScore: 1,
  },
  {
    id: 13,
    name: "Tezos (XTZ)",
    stakeRequirement: "6,000 XTZ",
    hardwareSummary: "4 cores, 8–16GB RAM",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "5–7%",
    aprSort: 6,
    notes: "Liquid PoS; classic home baker setup.",
    category: "AltL1",
    hardwareScore: 1,
  },
  {
    id: 14,
    name: "Cardano",
    stakeRequirement: "No strict min; pledge recommended",
    hardwareSummary: "2–4 cores, 16GB RAM, SSD",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "3–5%",
    aprSort: 4,
    notes: "Stake pools widely run from home or small servers.",
    category: "AltL1",
    hardwareScore: 1,
  },
  {
    id: 15,
    name: "Fantom",
    stakeRequirement: "500,000 FTM",
    hardwareSummary: "8 cores, 32GB RAM",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "8–13%",
    aprSort: 10,
    notes: "aBFT consensus; heavier hardware and higher stake.",
    category: "EVM",
    hardwareScore: 2,
  },
  {
    id: 16,
    name: "Harmony (ONE)",
    stakeRequirement: "10,000 ONE",
    hardwareSummary: "4–8 cores, 16GB RAM",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "7–10%",
    aprSort: 9,
    notes: "Effective PoS with sharding; home rigs are sufficient.",
    category: "AltL1",
    hardwareScore: 1,
  },
  {
    id: 17,
    name: "Akash Network",
    stakeRequirement: "Minimal stake",
    hardwareSummary: "4–8 cores, optional GPU",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "5–20%",
    aprSort: 12,
    notes: "DePIN-style; earn from validator role + cloud provider workloads.",
    category: "DePIN",
    hardwareScore: 2,
  },
  {
    id: 18,
    name: "Flux",
    stakeRequirement: "1k–12.5k FLUX",
    hardwareSummary: "4–8 cores, 8–32GB RAM",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "8–14%",
    aprSort: 11,
    notes: "Tiered node system designed for home and VPS hardware.",
    category: "DePIN",
    hardwareScore: 2,
  },
  {
    id: 19,
    name: "MultiversX (Elrond)",
    stakeRequirement: "2,500 EGLD",
    hardwareSummary: "8 cores, 16GB RAM",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "7–10%",
    aprSort: 9,
    notes: "Observer nodes + validators; good fit for home rigs.",
    category: "AltL1",
    hardwareScore: 2,
  },
  {
    id: 20,
    name: "Sui",
    stakeRequirement: "High self-bond (tens of millions of SUI)",
    hardwareSummary: "8–16 cores, 32–64GB RAM, NVMe",
    homeNodeFeasible: true,
    validatorHomeFeasible: "partial",
    aprRange: "2–5%",
    aprSort: 3,
    notes: "Full nodes are home-friendly; validators skew institutional.",
    category: "AltL1",
    hardwareScore: 2,
  },
  {
    id: 21,
    name: "Mina Protocol",
    stakeRequirement: "Minimal (light chain)",
    hardwareSummary: "Very light; even Raspberry Pi capable",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "4–7%",
    aprSort: 6,
    notes: "Ultra-lightweight zk chain; built for many nodes.",
    category: "AltL1",
    hardwareScore: 1,
  },
  {
    id: 22,
    name: "Celo",
    stakeRequirement: "10k–15k CELO",
    hardwareSummary: "4–8 cores, 16GB RAM",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "5–7%",
    aprSort: 6,
    notes: "Mobile-first PoS; moving toward Ethereum L2 but still home-node friendly.",
    category: "EVM",
    hardwareScore: 1,
  },
  {
    id: 23,
    name: "Sei",
    stakeRequirement: "Variable",
    hardwareSummary: "4–8 cores, 16GB RAM",
    homeNodeFeasible: true,
    validatorHomeFeasible: "yes",
    aprRange: "8–12%",
    aprSort: 10,
    notes: "Fast Cosmos-based chain; familiar node tooling.",
    category: "Cosmos",
    hardwareScore: 2,
  },
  {
    id: 24,
    name: "Aptos",
    stakeRequirement: "Permissioned validator set",
    hardwareSummary: "8–16 cores, 32GB RAM",
    homeNodeFeasible: true,
    validatorHomeFeasible: "no",
    aprRange: "7–10% (for approved validators)",
    aprSort: 8,
    notes: "Home full nodes are fine; validator role is restricted.",
    category: "AltL1",
    hardwareScore: 2,
  },
  {
    id: 25,
    name: "Starknet",
    stakeRequirement: "No open validator role yet",
    hardwareSummary: "High-spec recommended for full nodes",
    homeNodeFeasible: true,
    validatorHomeFeasible: "no",
    aprRange: "N/A (no permissionless validator rewards)",
    aprSort: 0,
    notes: "ZK rollup; full nodes possible, sequencer/validator role centralized.",
    category: "L2",
    hardwareScore: 3,
  },
];
